export const navigations = [
  {
    title: 'Category',
    href: '/',
  },
  {
    title: 'Đang chiếu',
    href: '/',
  },
  {
    title: 'Phim sắp chiếu',
    href: '/',
  },
  {
    title: 'Phim phổ biến',
    href: '/',
  },
  {
    title: 'year',
    href: '/',
  },
]

export const carousels = [
  {
    name: 'The Green Mile',
    imgUrl: 'https://image.tmdb.org/t/p/w1280/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
    description:
      'A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people',
  },
  {
    name: 'Pulp Fiction',
    imgUrl: 'https://image.tmdb.org/t/p/w1280/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
    description: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster',
  },
  {
    name: 'The Dark Knight',
    imgUrl: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    description: 'Content 1',
  },
]

export const movies = [
  {
    adult: false,
    backdrop_path: '/1syW9SNna38rSl9fnXwc9fP7POW.jpg',
    genre_ids: [28, 878, 12],
    id: 565770,
    original_language: 'en',
    original_title: 'Blue Beetle',
    overview:
      'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
    popularity: 2706.353,
    poster_path: '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
    release_date: '2023-08-16',
    title: 'Blue Beetle',
    video: false,
    vote_average: 7.1,
    vote_count: 1096,
  },
  {
    adult: false,
    backdrop_path: '/jv4tiXAgaArMQo57jFMjvBEjmoa.jpg',
    genre_ids: [28, 18, 12],
    id: 980489,
    original_language: 'en',
    original_title: 'Gran Turismo',
    overview:
      'The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
    popularity: 3752.83,
    poster_path: '/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg',
    release_date: '2023-08-09',
    title: 'Gran Turismo',
    video: false,
    vote_average: 8,
    vote_count: 724,
  },
  {
    adult: false,
    backdrop_path: '/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg',
    genre_ids: [28, 878, 27],
    id: 615656,
    original_language: 'en',
    original_title: 'Meg 2: The Trench',
    overview:
      'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
    popularity: 1519.064,
    poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
    release_date: '2023-08-02',
    title: 'Meg 2: The Trench',
    video: false,
    vote_average: 6.9,
    vote_count: 2098,
  },
  {
    adult: false,
    backdrop_path: '/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg',
    genre_ids: [28, 9648, 53, 80],
    id: 762430,
    original_language: 'en',
    original_title: 'Retribution',
    overview:
      'While driving his kids to school, a Berlin financier receives a call from a mysterious man claiming that a bomb has been installed under his seat and will be detonated if anyone tries to leave the car or refuses his demands.',
    popularity: 1288.533,
    poster_path: '/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg',
    release_date: '2023-08-23',
    title: 'Retribution',
    video: false,
    vote_average: 6.8,
    vote_count: 277,
  },
  {
    adult: false,
    backdrop_path: '/53z2fXEKfnNg2uSOPss2unPBGX1.jpg',
    genre_ids: [27, 9648, 53],
    id: 968051,
    original_language: 'en',
    original_title: 'The Nun II',
    overview:
      'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
    popularity: 1333.942,
    poster_path: '/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg',
    release_date: '2023-09-06',
    title: 'The Nun II',
    video: false,
    vote_average: 6.5,
    vote_count: 368,
  },
  {
    adult: false,
    backdrop_path: '/waBWlJlMpyFb7STkFHfFvJKgwww.jpg',
    genre_ids: [28, 18],
    id: 678512,
    original_language: 'en',
    original_title: 'Sound of Freedom',
    overview:
      'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
    popularity: 1338.53,
    poster_path: '/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg',
    release_date: '2023-07-03',
    title: 'Sound of Freedom',
    video: false,
    vote_average: 7.9,
    vote_count: 513,
  },
  {
    adult: false,
    backdrop_path: '/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg',
    genre_ids: [27, 53],
    id: 1008042,
    original_language: 'en',
    original_title: 'Talk to Me',
    overview:
      'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
    popularity: 1112.41,
    poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
    release_date: '2023-07-26',
    title: 'Talk to Me',
    video: false,
    vote_average: 7.2,
    vote_count: 987,
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 1175.501,
    poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    release_date: '2023-05-17',
    title: 'Fast X',
    video: false,
    vote_average: 7.3,
    vote_count: 3910,
  },
  {
    adult: false,
    backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
    genre_ids: [35, 12, 14],
    id: 346698,
    original_language: 'en',
    original_title: 'Barbie',
    overview:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    popularity: 1049.234,
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    release_date: '2023-07-19',
    title: 'Barbie',
    video: false,
    vote_average: 7.3,
    vote_count: 5165,
  },
  {
    adult: false,
    backdrop_path: '/zYlgqIpqJ1VAbvFhRhktAzIybVs.jpg',
    genre_ids: [27, 878, 53],
    id: 820609,
    original_language: 'en',
    original_title: 'No One Will Save You',
    overview: "An exiled anxiety-ridden homebody must battle an alien who's found its way into her home.",
    popularity: 1185.061,
    poster_path: '/ehGIDAMaYy6Eg0o8ga0oqflDjqW.jpg',
    release_date: '2023-09-22',
    title: 'No One Will Save You',
    video: false,
    vote_average: 6.9,
    vote_count: 389,
  },
  {
    adult: false,
    backdrop_path: '/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg',
    genre_ids: [16, 35, 10751, 14, 10749],
    id: 976573,
    original_language: 'en',
    original_title: 'Elemental',
    overview:
      'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
    popularity: 764.416,
    poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
    release_date: '2023-06-14',
    title: 'Elemental',
    video: false,
    vote_average: 7.8,
    vote_count: 2481,
  },
  {
    adult: false,
    backdrop_path: '/oghHR3X0hIcvs7xqyoFjA0GAZWn.jpg',
    genre_ids: [53],
    id: 1002338,
    original_language: 'is',
    original_title: 'Napóleonsskjölin',
    overview:
      "A modern-day lawyer is sucked into an international conspiracy after being accused of a murder she didn't commit. Her only chance of freedom lies in uncovering the secret of an old German WWII aeroplane, long buried deep beneath the ice, before the CIA.",
    popularity: 718.419,
    poster_path: '/j2Or0w69bpPXrmkE0hpTzw6hzsr.jpg',
    release_date: '2023-01-26',
    title: 'Operation Napoleon',
    video: false,
    vote_average: 7,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: '/5xUJBgds96m6Xi2EtUpSzbw24D7.jpg',
    genre_ids: [53, 9648],
    id: 852436,
    original_language: 'fr',
    original_title: 'Seule : Les dossiers Silvercloud',
    overview:
      'Alone in the mountains of Switzerland, Anne discovers that her isolated chalet is on surveillance and has been bugged. Caught up by her former life as an intelligence secret agent and an affair with her handler, Anne can only count on herself to get out alive.',
    popularity: 751.118,
    poster_path: '/qx81rP4b4UFcxjabCqfe79F24Z0.jpg',
    release_date: '2023-03-08',
    title: 'Let Her Kill You',
    video: false,
    vote_average: 6.9,
    vote_count: 56,
  },
  {
    adult: false,
    backdrop_path: '/9b3uxqcjkmay20EBZZj1KVow0r5.jpg',
    genre_ids: [80, 27, 53],
    id: 951491,
    original_language: 'en',
    original_title: 'Saw X',
    overview:
      "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
    popularity: 987.796,
    poster_path: '/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg',
    release_date: '2023-09-26',
    title: 'Saw X',
    video: false,
    vote_average: 7.4,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: '/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg',
    genre_ids: [28, 53],
    id: 717930,
    original_language: 'en',
    original_title: 'Kandahar',
    overview:
      'After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.',
    popularity: 691.37,
    poster_path: '/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg',
    release_date: '2023-05-25',
    title: 'Kandahar',
    video: false,
    vote_average: 6.9,
    vote_count: 586,
  },
  {
    adult: false,
    backdrop_path: '/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg',
    genre_ids: [12, 28],
    id: 335977,
    original_language: 'en',
    original_title: 'Indiana Jones and the Dial of Destiny',
    overview:
      "Finding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
    popularity: 652.204,
    poster_path: '/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg',
    release_date: '2023-06-28',
    title: 'Indiana Jones and the Dial of Destiny',
    video: false,
    vote_average: 6.7,
    vote_count: 1792,
  },
  {
    adult: false,
    backdrop_path: '/iOJX54nVAsnPawagFiWXKv1Y6sB.jpg',
    genre_ids: [16, 12, 10751],
    id: 1076364,
    original_language: 'en',
    original_title: "Carl's Date",
    overview:
      "Carl Fredricksen reluctantly agrees to go on a date with a lady friend—but admittedly has no idea how dating works these days. Ever the helpful friend, Dug steps in to calm Carl's pre-date jitters and offer some tried-and-true tips for making friends—if you're a dog.",
    popularity: 596.191,
    poster_path: '/y8NtM6q3PzntqyNRNw6wgicwRYl.jpg',
    release_date: '2023-06-15',
    title: "Carl's Date",
    video: false,
    vote_average: 7.8,
    vote_count: 204,
  },
  {
    adult: false,
    backdrop_path: '/9WxqnP9c29wXd03sALSpxpTx8fk.jpg',
    genre_ids: [9648, 53, 28],
    id: 1172009,
    original_language: 'en',
    original_title: 'The Black Book',
    overview:
      'After his son is wrongly accused of kidnapping, a deacon who has just lost his wife takes matters into his own hands and fights a crooked police gang to clear him.',
    popularity: 912.178,
    poster_path: '/kn28W24slBLyGr8ZIZnxNE5YZrY.jpg',
    release_date: '2023-09-22',
    title: 'The Black Book',
    video: false,
    vote_average: 7.8,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/uAAAzo9efEZJJPtj4iNwFvrRaki.jpg',
    genre_ids: [28, 80, 878, 18],
    id: 744278,
    original_language: 'it',
    original_title: 'Mondocane',
    overview:
      'In the near future, the southern Italian city of Taranto is surrounded by barbed wire that no one, not even the police, dares to cross. The poorest are left fighting for survival, while gangs compete for the territory. Two thirteen-year-old orphans who grew up together, dream of joining one of the gangs.',
    popularity: 608.73,
    poster_path: '/gOuJBz9u1YVWwvx12lJX56yUT6I.jpg',
    release_date: '2021-09-03',
    title: 'Mondocane',
    video: false,
    vote_average: 6.5,
    vote_count: 116,
  },
  {
    adult: false,
    backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
    genre_ids: [28, 12, 878],
    id: 667538,
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview:
      'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
    popularity: 603.442,
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    release_date: '2023-06-06',
    title: 'Transformers: Rise of the Beasts',
    video: false,
    vote_average: 7.5,
    vote_count: 3287,
  },
]

export const trendings = [
  {
    adult: false,
    backdrop_path: '/xvzxqKWltnj6qSiWBXRq6ZCdcrw.jpg',
    id: 1151534,
    title: 'Nowhere',
    original_language: 'es',
    original_title: 'Nowhere',
    overview:
      'A young pregnant woman named Mia escapes from a country at war by hiding in a maritime container aboard a cargo ship. After a violent storm, Mia gives birth to the child while lost at sea, where she must fight to survive.',
    poster_path: '/rpzFxv78UvYG5yQba2soO5mMl4T.jpg',
    media_type: 'movie',
    genre_ids: [53, 18],
    popularity: 199.455,
    release_date: '2023-09-29',
    video: false,
    vote_average: 7.854,
    vote_count: 247,
  },
  {
    adult: false,
    backdrop_path: '/nrp2khEM6JWFqqNLeub1J6Qafe0.jpg',
    id: 866463,
    title: 'Reptile',
    original_language: 'en',
    original_title: 'Reptile',
    overview:
      'Following the brutal murder of a young real estate agent, a hardened detective attempts to uncover the truth in a case where nothing is as it seems, and by doing so dismantles the illusions in his own life.',
    poster_path: '/soIgqZBoTiTgMqUW0JtxsPWAilQ.jpg',
    media_type: 'movie',
    genre_ids: [53, 80, 18, 9648],
    popularity: 208.134,
    release_date: '2023-09-29',
    video: false,
    vote_average: 7.119,
    vote_count: 88,
  },
  {
    adult: false,
    backdrop_path: '/628Dep6AxEtDxjZoGP78TsOxYbK.jpg',
    id: 575264,
    title: 'Mission: Impossible - Dead Reckoning Part One',
    original_language: 'en',
    original_title: 'Mission: Impossible - Dead Reckoning Part One',
    overview:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
    poster_path: '/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 697.251,
    release_date: '2023-07-08',
    video: false,
    vote_average: 7.724,
    vote_count: 1200,
  },
  {
    adult: false,
    backdrop_path: '/8BNA9L3JEJeMN7S21fzo9SeYUtU.jpg',
    id: 1081662,
    title: 'Appendage',
    original_language: 'en',
    original_title: 'Appendage',
    overview:
      "After hitting a breaking point, Hannah's inner thoughts physicalize into a monstrous creature that threatens to upend her life.",
    poster_path: '/mGwDi4MuvMiQS2G9mcSXDRZjttx.jpg',
    media_type: 'movie',
    genre_ids: [27, 9648, 53, 35, 18],
    popularity: 11.659,
    release_date: '2023-03-11',
    video: false,
    vote_average: 5.7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/xFYpUmB01nswPgbzi8EOCT1ZYFu.jpg',
    id: 980489,
    title: 'Gran Turismo',
    original_language: 'en',
    original_title: 'Gran Turismo',
    overview:
      'The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
    poster_path: '/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg',
    media_type: 'movie',
    genre_ids: [28, 18, 12],
    popularity: 3752.83,
    release_date: '2023-08-09',
    video: false,
    vote_average: 8.044,
    vote_count: 732,
  },
  {
    adult: false,
    backdrop_path: '/9b3uxqcjkmay20EBZZj1KVow0r5.jpg',
    id: 951491,
    title: 'Saw X',
    original_language: 'en',
    original_title: 'Saw X',
    overview:
      "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
    poster_path: '/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg',
    media_type: 'movie',
    genre_ids: [80, 27, 53],
    popularity: 987.796,
    release_date: '2023-09-26',
    video: false,
    vote_average: 7.382,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: '/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg',
    id: 670292,
    title: 'The Creator',
    original_language: 'en',
    original_title: 'The Creator',
    overview:
      'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
    poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
    media_type: 'movie',
    genre_ids: [878, 28, 53],
    popularity: 683.208,
    release_date: '2023-09-27',
    video: false,
    vote_average: 7.244,
    vote_count: 164,
  },
  {
    adult: false,
    backdrop_path: '/hrqPHNioMoCVyyh8FCcaINTv6Nu.jpg',
    id: 1172676,
    title: 'Poison',
    original_language: 'en',
    original_title: 'Poison',
    overview:
      "When a poisonous snake slithers onto an Englishman's stomach in India, his associate and a doctor race to save him.",
    poster_path: '/evgEvYCUGidCyUCxA77EUJiWpVQ.jpg',
    media_type: 'movie',
    genre_ids: [35],
    popularity: 106.996,
    release_date: '2023-09-30',
    video: false,
    vote_average: 7.068,
    vote_count: 44,
  },
  {
    adult: false,
    backdrop_path: '/dS4JR8gmj8UnamjuLEyAkEFoppy.jpg',
    id: 923939,
    title: 'The Wonderful Story of Henry Sugar',
    original_language: 'en',
    original_title: 'The Wonderful Story of Henry Sugar',
    overview:
      'A rich man learns about a guru who can see without using his eyes. He sets out to master the skill in order to cheat at gambling.',
    poster_path: '/A4LTXT8MMZIr4aIwhE4qbGFivBo.jpg',
    media_type: 'movie',
    genre_ids: [14, 35, 12],
    popularity: 264.61,
    release_date: '2023-09-20',
    video: false,
    vote_average: 7.5,
    vote_count: 203,
  },
  {
    adult: false,
    backdrop_path: '/nV4nOG6ZCK8orRL7T5wXXgMdM0N.jpg',
    id: 1059811,
    title: 'Flora and Son',
    original_language: 'en',
    original_title: 'Flora and Son',
    overview:
      'Single mum Flora is at a loss about what to do with her rebellious teenage son, Max. Her efforts to keep him out of trouble lead to a beat-up acoustic guitar, a washed-up LA musician, and harmony for this frayed Dublin family.',
    poster_path: '/pq2p8ovf8PZps2HafvJaLrZK8gS.jpg',
    media_type: 'movie',
    genre_ids: [10402, 35, 18],
    popularity: 87.192,
    release_date: '2023-09-21',
    video: false,
    vote_average: 7.2,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: '/o4SBV32WdZZOd9mV9ng7zUUWG70.jpg',
    id: 678512,
    title: 'Sound of Freedom',
    original_language: 'en',
    original_title: 'Sound of Freedom',
    overview:
      'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
    poster_path: '/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg',
    media_type: 'movie',
    genre_ids: [28, 18],
    popularity: 1338.53,
    release_date: '2023-07-03',
    video: false,
    vote_average: 7.937,
    vote_count: 514,
  },
  {
    adult: false,
    backdrop_path: '/1syW9SNna38rSl9fnXwc9fP7POW.jpg',
    id: 565770,
    title: 'Blue Beetle',
    original_language: 'en',
    original_title: 'Blue Beetle',
    overview:
      'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
    poster_path: '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
    media_type: 'movie',
    genre_ids: [28, 878, 12],
    popularity: 2706.353,
    release_date: '2023-08-16',
    video: false,
    vote_average: 7.127,
    vote_count: 1097,
  },
  {
    adult: false,
    backdrop_path: '/jP3FatCTHc460ZGW57q9ypTdBqu.jpg',
    id: 937249,
    title: '57 Seconds',
    original_language: 'en',
    original_title: '57 Seconds',
    overview:
      'When a tech blogger lands an interview with a tech guru and stops an attack on him, he finds a mysterious ring that takes him back 57 seconds into the past.',
    poster_path: '/dfS5qHWFuXyZQnwYREwb7N4qU5p.jpg',
    media_type: 'movie',
    genre_ids: [53, 878],
    popularity: 95.628,
    release_date: '2023-09-29',
    video: false,
    vote_average: 6.1,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: '/su7FqHdZez0oOvpZAbV7P6BGq0R.jpg',
    id: 939335,
    title: 'Muzzle',
    original_language: 'en',
    original_title: 'Muzzle',
    overview:
      'LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a chokehold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.',
    poster_path: '/qXChf7MFL36BgoLkiB3BzXiwW82.jpg',
    media_type: 'movie',
    genre_ids: [28, 80, 18, 53],
    popularity: 171.891,
    release_date: '2023-09-29',
    video: false,
    vote_average: 6,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: '/aQuzqump4Zjh2bCoymZ2POLlNYt.jpg',
    id: 1172674,
    title: 'The Rat Catcher',
    original_language: 'en',
    original_title: 'The Rat Catcher',
    overview:
      'In an English village, a reporter and a mechanic listen to a ratcatcher explain his clever plan to outwit his prey.',
    poster_path: '/29WJ7dOHt48AtXK1J1rONEEvIMN.jpg',
    media_type: 'movie',
    genre_ids: [35],
    popularity: 152.984,
    release_date: '2023-09-29',
    video: false,
    vote_average: 6.794,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
    id: 346698,
    title: 'Barbie',
    original_language: 'en',
    original_title: 'Barbie',
    overview:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    media_type: 'movie',
    genre_ids: [35, 12, 14],
    popularity: 1049.234,
    release_date: '2023-07-19',
    video: false,
    vote_average: 7.3,
    vote_count: 5168,
  },
  {
    adult: false,
    backdrop_path: '/zYlgqIpqJ1VAbvFhRhktAzIybVs.jpg',
    id: 820609,
    title: 'No One Will Save You',
    original_language: 'en',
    original_title: 'No One Will Save You',
    overview: "An exiled anxiety-ridden homebody must battle an alien who's found its way into her home.",
    poster_path: '/ehGIDAMaYy6Eg0o8ga0oqflDjqW.jpg',
    media_type: 'movie',
    genre_ids: [27, 878, 53],
    popularity: 1185.061,
    release_date: '2023-09-22',
    video: false,
    vote_average: 6.951,
    vote_count: 389,
  },
  {
    adult: false,
    backdrop_path: '/efro4duB7agkA2Xl5LmkD3HeCim.jpg',
    id: 818511,
    title: 'Overhaul',
    original_language: 'pt',
    original_title: 'Carga Máxima',
    overview:
      'When truck racer Roger loses everything, he receives a tempting but dangerous offer: to work as the getaway driver for a gang of thieves.',
    poster_path: '/6yx14lSACNJ2zRoYyXqecf3QNgr.jpg',
    media_type: 'movie',
    genre_ids: [28, 53, 18],
    popularity: 205.702,
    release_date: '2023-09-27',
    video: false,
    vote_average: 7.3,
    vote_count: 41,
  },
  {
    adult: false,
    backdrop_path: '/oIUDSK3CCqkpe6lct8YPuUupFes.jpg',
    id: 1172675,
    title: 'The Swan',
    original_language: 'en',
    original_title: 'The Swan',
    overview:
      'Two large, ignorant bullies ruthlessly pursue a small, brilliant boy in this young adult Roald Dahl short story.',
    poster_path: '/fRbx6DPdQBJrhZWyshjJABtAIyu.jpg',
    media_type: 'movie',
    genre_ids: [35],
    popularity: 172.224,
    release_date: '2023-09-28',
    video: false,
    vote_average: 7.107,
    vote_count: 61,
  },
  {
    adult: false,
    backdrop_path: '/1DBo2V4KyBWXuagt4JOR2jZJMHB.jpg',
    id: 1171541,
    title: 'Sniper: G.R.I.T. - Global Response & Intelligence Team',
    original_language: 'en',
    original_title: 'Sniper: G.R.I.T. - Global Response & Intelligence Team',
    overview:
      'When an international terrorist cult threatens global political stability and kidnaps a fellow agent, Ace Sniper Brandon Beckett and the newly-formed Global Response & Intelligence Team – or G.R.I.T. – led by Colonel Stone must travel across the world to Malta, infiltrate the cult, and take out its leader to free Lady Death and stop the global threat.',
    poster_path: '/gcd5TJwXLWeQ2Dn0aRxI8OJIIxK.jpg',
    media_type: 'movie',
    genre_ids: [28, 53],
    popularity: 443.89,
    release_date: '2023-09-26',
    video: false,
    vote_average: 7.071,
    vote_count: 14,
  },
]
